### ISSUE TITLE
Key size 128

### ISSUE THREAD

**Issue by drveresh** [harshkanjariya/any-steganography#4]
As per the statement "encryption key with length 128", is it in bits or bytes?

I tried with the key "ASDFGHJKLASDFGHJ", but it failed with the below error. Please help me.

```
internal/crypto/cipher.js:79
    this._handle.initiv(cipher, credential, iv, authTagLength);
                 ^

Error: Invalid key length
    at Cipheriv.createCipherBase (internal/crypto/cipher.js:79:18)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:115:20)
    at new Cipheriv (internal/crypto/cipher.js:217:22)
    at Object.createCipheriv (crypto.js:109:10)
    at Object.encrypt (<PATH>/any-steganography/dist/security.js:58:27)
    at Function.write (<PATH>/any-steganography/dist/steganography.class.js:66:37)
    at Object.<anonymous> (<PATH>/MyProject/photo.js:10:27)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)

```

**Comment by harshkanjariya** [comment]
Yes! first of all thank you for pointing out this. It is a mistake of documentation. Actually the encryption algorithm used is aes-256 so it will need 256 bit key. So you can try with 32 characters
